travis:
  secure:
    BINSTAR_TOKEN: vNQMEHrsaTqMX6ULBMbxut8p/Iou4yfXxsCxvZBlqphThzw+I7BvcAYowNpp6JP8jT8VRDLuekZxLTv/TvXJqLeY/IID/Pdu1SjM0MrI35gkK4pCLtQYCctOnToe2ccahMjyy3YSsXm+eRtVYwVv7Sfm4nhhyfh8Jx1SPou8soVJMTCcNZDcWDnRu9sNeHe8ONL0Nh9aQn6q18xwjI998eR/5blgsBnLco+4lckxzL7sX8a6eC9L1LdocRiooGv6TWABvdGbikuEmrfiXB9CB3MlGhrOQYHrwlFdCesz9Z4u1b76mGAvH4rBzKQIZp4zsYIA9dVVKYH1kAfBoiQ5m0J9//eWX+HCADz2XrDf9cSdcgi2gZTAsEZQ7b2VPA3QOPd4SqCNpjZ+vFyPWI2ElZ0tRyvTwCRTpR3uk45q6UaB2WJi4YaqTreSMJecm457/NBCRYc7V7Of+Acg3ef0DjX9HQJ15dpqgKFirFaDdPLDlWkm9iEhVTS/I+MIBVEFMpn/78HROe7Iq6CKKbAUAhnq+JbxB/2VBGPyYeazHzpG6z9gKL1rKu7NEtJ7rBewZeXVe9wnF0k4oWCFSuFSBAI6Oe42fkpBAaavARC2qDi7EggCxFXza1lPq4fwtGJGDjRcexovCBXOlenUiUeVMZ/JcaeTYLMVlIbUG7F1sYU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
