appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: iy4hlfIVbeeiyHqu86TETZDGGf3ScwKeZPE9yTrySEtEG2MOoy6TxImb3t5qAhawtWpQc34iQhvDR6w2dbYAWJzd+H4aRc4V2VK4JaRw9HStSVaRk+iDcpxY7VRnPWwPoBIouGZD91SNTEEL6OwwkNEFNWD8zebNJO5dEo9tNF4iqfhGaM41lsipvAFhOceFRWdaXhv+MASW4NrgGdFFcCePTZtGAYHseNYOURgO+C4aBuiwXs6rlOeE40zMitXc9gi3/8eH3tU6bQZZPfSSKUpzaH2XVBh/k0GKkqAzGh/ZsJ8Go1fR7/6WtHnDGh+3P9q3XIjdHPVefFEEPE7AzdE6KeDiarNXoxhZ+s2vqeSVj+EELCfurgE3CO5GXR6h/yEWxiG+z4wOL0KQA5oidypqsIDppmW1Vcjgc5uSavQmtdWCL9BXj9xdx0vobnHFG1CUDdRoPlntDdAhEiEvKVXyJsb87aNSJ4/sYUrvVwkVdZc7Fyl16Ez4CKIftQv02E0E9ppkerEgVdlAgCFe/DnDafjymnpaSAOwaHIz3RpLEzqD67Or3yH7B1fCrTrMJ4buqZ2OEoXy0Z/XQ52CzcuNI6vAZmJjwV0QWs/aKuIFzKt7Xyftspthnlb3EF5B8hypEKzUard3aDHL7d4C2z+eGi4QpGePIHDxIhQCSz4=
conda_forge_output_validation: true
